const myFunction = () => {
    return new Promise((resolve, reject) => {
        if (false) {
            resolve('Yeah!');
        } else {
            reject('Whoops');
        }
    })
}

myFunction()
    .then(response => console.log(response))
    .catch(err => console.log(err))
    //acÃ¡ sigue
    .finally(() => console.log('Finally!!!'));